import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from 'next-themes'
import { LayoutThemeProvider } from "@/components/providers/LayoutThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LayoutThemeProvider attribute="class" defaultTheme="dark" disableTransitionOnChange forcedTheme="dark">
          {children}
        </LayoutThemeProvider>
      </body>
    </html>
  );
}
