import { LayoutThemeProvider } from "@/components/providers/LayoutThemeProvider";
import type { Metadata } from "next";
import { Anek_Odia } from "next/font/google";
import "./globals.css";

const inter = Anek_Odia({ 
  weight: ["800"],
  subsets: ["latin"],
  style: ["normal",],
 });

export const metadata: Metadata = {
  title: "Reactive - Online Cloud IdE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LayoutThemeProvider attribute="class" defaultTheme="dark" disableTransitionOnChange forcedTheme="dark">
        
          {children}
        </LayoutThemeProvider>
      </body>
    </html>
  );
}
